### ISSUE TITLE
CS - 3 MAD

### ISSUE THREAD

**Issue by mvalbuquerque** [greenway-FIAP/mobile#1]
Olá! Não estou conseguindo corrigir o CS qual é o usuário e senha de acesso?

E esta dando este erro ;-) @kaique100 

![Screenshot_1726604514](https://github.com/user-attachments/assets/fe4b9372-096d-485e-aa1e-8cd108b8c016)

**Comment by kaique100** [comment]
Usuário: Kaique
Senha: 123

**Comment by mvalbuquerque** [comment]
Obrigado! Deu certo. Abs.
