### ISSUE TITLE
CS - 3 Error .

### ISSUE THREAD

**Issue by mvalbuquerque** [greenway-FIAP/mobile#2]
@kaique100 

![Captura de Tela 2024-09-17 às 17 22 04](https://github.com/user-attachments/assets/b287e2f8-93f6-477a-97e5-a804a3419427)

**Comment by marceloamellopaixao** [comment]
Professor, este erro não está acarretando em nenhum mal funcionamento na aplicação, pois ao logar com o Usuário e Senha que o Kaique informou, funciona normalmente.
